### ISSUE TITLE
Just gets stuck at first mod in manifest now

### ISSUE THREAD

**Issue by SmallSansSerif** [portablejim/curseDownloader#16]
Did this stop working? I haven't been able to get this to download packs lately.

<img width="605" alt="screen shot 2016-04-29 at 5 00 13 pm" src="https://cloud.githubusercontent.com/assets/4984139/14929531/db4531b4-0e2b-11e6-91ca-3d3f11cac549.png">

**Comment by MrThomson** [comment]
having the same issue seems to impact any pack that are not verison 1.7.10. have issue with 1.8.9 packs and 1.9

Hope this software keeps getting updated

**Comment by dogpound** [comment]
Trying to download WyldLife 1.1

~/temp/curseDownloader-0.2$ python3.5 downloader.py manifest.json

65 files to download
[1/65] Mantle-1.10.2-1.1.0.jar
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "downloader.py", line 65, in goDownloadBackground
    doDownload(self.manifestPath.get())
  File "downloader.py", line 143, in doDownload
    with open(str(minecraftPath / "mods" / fileName), "wb") as mod:
FileNotFoundError: [Errno 2] No such file or directory: '/home/dogpound/temp/curseDownloader-0.2/minecraft/mods/Mantle-1.10.2-1.1.0.jar'
