### ISSUE TITLE
[Bug] Can not download new packs

### ISSUE THREAD

**Issue by Dijkstra1** [portablejim/curseDownloader#25]
when I tried to download an update for a pack i was playing, I got this:
 ```Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\requests\adapters.py", line 370, in send
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 544, in urlopen
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 341, in _make_request
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 762, in _validate_conn
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connection.py", line 238, in connect
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\util\ssl_.py", line 255, in ssl_wrap_socket
requests.packages.urllib3.exceptions.SSLError: [Errno 2] No such file or directory11```

Some thing similar on Linux as well, I even download python 3.4 to my windows os and guess what, it still happens it worked fine with older version of the pack, witch was only released last Firday (15th).

I am guessing the cruse have changed something in the pack manifest files work.

**Comment by phreekbird** [comment]
Same here, Ubuntu 16.04.1 x86_64.
Everything looks like its going to run, the gui pops up, I select my json file, click download, and this is the output in the terminal.



$ sudo apt-get install python3 python3-tk python3-pip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3 is already the newest version (3.5.1-3).
python3-tk is already the newest version (3.5.1-1).
python3-pip is already the newest version (8.1.1-2ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
$ pip3 install appdirs
Collecting appdirs
  Using cached appdirs-1.4.0-py2.py3-none-any.whl
Installing collected packages: appdirs
Successfully installed appdirs-1.4.0
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
$ ./cursePackDownloader
88 files to download
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/python3.4.3/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 253, in ssl_wrap_socket
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python3.4.3/lib/python3.4/site-packages/requests/adapters.py", line 370, in send
  File "/opt/python3.4.3/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
  File "/opt/python3.4.3/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
  File "/opt/python3.4.3/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 762, in _validate_conn
  File "/opt/python3.4.3/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 238, in connect
  File "/opt/python3.4.3/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 255, in ssl_wrap_socket
requests.packages.urllib3.exceptions.SSLError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python3.4.3/lib/python3.4/threading.py", line 920, in _bootstrap_inner
  File "/opt/python3.4.3/lib/python3.4/threading.py", line 868, in run
  File "downloader.py", line 65, in goDownloadBackground
  File "downloader.py", line 134, in doDownload
  File "/opt/python3.4.3/lib/python3.4/site-packages/requests/sessions.py", line 476, in get
  File "/opt/python3.4.3/lib/python3.4/site-packages/requests/sessions.py", line 464, in request
  File "/opt/python3.4.3/lib/python3.4/site-packages/requests/sessions.py", line 602, in send
  File "/opt/python3.4.3/lib/python3.4/site-packages/requests/sessions.py", line 602, in <listcomp>
  File "/opt/python3.4.3/lib/python3.4/site-packages/requests/sessions.py", line 195, in resolve_redirects
  File "/opt/python3.4.3/lib/python3.4/site-packages/requests/sessions.py", line 576, in send
  File "/opt/python3.4.3/lib/python3.4/site-packages/requests/adapters.py", line 431, in send
requests.exceptions.SSLError: [Errno 2] No such file or directory
$

**Comment by Truck3rCl0ck** [comment]
I have the same issue with Ubuntu 16.04.1 as well.

**Comment by k1ckcyph3r** [comment]
I have the same error in ubuntu 16.04 downloading a [1.10.2 modpack](https://mods.curse.com/modpacks/minecraft/242462-all-the-mods), but I used [this fork](https://github.com/TOLoneWolf/curseDownloader) and worked just fine:

![screen](http://i.imgur.com/9pNh0kg.png)

**Comment by dmodoomsirius** [comment]
I am having the same issue on windows latest release
