### ISSUE TITLE
SSL and 'Not a directory' error

### ISSUE THREAD

**Issue by Zero-Angel** [portablejim/curseDownloader#32]
Running this on Debian Stable 3.16.0-4-amd64 with Python 3.4 installed. I'm trying to use it to process the manifest.json that's in the Project Ozone 2-2.1.8 that i've downloaded from cursecdn. CPD states '152 files to download' and does not proceed.

Launching via the terminal shows this output:
```
┌─(david@eaglefeather)(18:39:09)(•)───────────────────────────────────────────(~/Program/cursePackDownloader-0.2-linux-64bit)─┐
└─(:))─> $ ./cursePackDownloader
Fontconfig error: "local.conf", line 1: XML or text declaration not at start of entity
152 files to download
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/python3.4.3/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 253, in ssl_wrap_socket
NotADirectoryError: [Errno 20] Not a directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python3.4.3/lib/python3.4/site-packages/requests/adapters.py", line 370, in send
  File "/opt/python3.4.3/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
  File "/opt/python3.4.3/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
  File "/opt/python3.4.3/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 762, in _validate_conn
  File "/opt/python3.4.3/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 238, in connect
  File "/opt/python3.4.3/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 255, in ssl_wrap_socket
requests.packages.urllib3.exceptions.SSLError: [Errno 20] Not a directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python3.4.3/lib/python3.4/threading.py", line 920, in _bootstrap_inner
  File "/opt/python3.4.3/lib/python3.4/threading.py", line 868, in run
  File "downloader.py", line 65, in goDownloadBackground
  File "downloader.py", line 134, in doDownload
  File "/opt/python3.4.3/lib/python3.4/site-packages/requests/sessions.py", line 476, in get
  File "/opt/python3.4.3/lib/python3.4/site-packages/requests/sessions.py", line 464, in request
  File "/opt/python3.4.3/lib/python3.4/site-packages/requests/sessions.py", line 602, in send
  File "/opt/python3.4.3/lib/python3.4/site-packages/requests/sessions.py", line 602, in <listcomp>
  File "/opt/python3.4.3/lib/python3.4/site-packages/requests/sessions.py", line 195, in resolve_redirects
  File "/opt/python3.4.3/lib/python3.4/site-packages/requests/sessions.py", line 576, in send
  File "/opt/python3.4.3/lib/python3.4/site-packages/requests/adapters.py", line 431, in send
requests.exceptions.SSLError: [Errno 20] Not a directory
```
The fontconfig error/notice is common on my machine and should not affect the problem.

**Comment by majix560** [comment]
Use [this fork](https://github.com/TOLoneWolf/curseDownloader) instead.
I found it thanks to this other issue more-or-less of the same problem as you.
https://github.com/portablejim/curseDownloader/issues/25

**Comment by Zero-Angel** [comment]
The TOLoneWolf fork worked for me. Thanks.
