### ISSUE TITLE
No Attribute 'is_redirect'

### ISSUE THREAD

**Issue by HeroCC** [portablejim/curseDownloader#41]
Running git 33d01f1ebf4cc796a022f74ea620b18e733c4069, I run the downloader, and I get this error:
```
162 files to download
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "downloader.py", line 71, in goDownloadBackground
    doDownload(self.manifestPath.get())
  File "downloader.py", line 163, in doDownload
    while fileResponse.is_redirect:
AttributeError: 'Response' object has no attribute 'is_redirect'
```
Ubuntu 14.04, with [this modpack](https://mods.curse.com/modpacks/minecraft/244939-project-ozone-2-reloaded). Any idea what's up?

Thanks!

**Comment by TOLoneWolf** [comment]
Would help to known which version of the pack as well.

Probably because some of the mods linked in the manifest are missing the specific version the pack is using. Some mods like to remove older versions from curse.
Example: https://minecraft.curseforge.com/projects/cofhcore/files/2320124/download is missing for Project Ozone 2: Reloaded 2.2.6 EFU3 which is probably what is making "fileResponse.is_redirect" not get set resulting in that error.
https://github.com/portablejim/curseDownloader/blob/33d01f1ebf4cc796a022f74ea620b18e733c4069/downloader.py#L163
