### ISSUE TITLE
Path Not Found?

### ISSUE THREAD

**Issue by blueboy90780** [portablejim/curseDownloader#44]
When I tried downloading Agrarian Skies 2 Modpack, I attach the JSON file and it returns me an error:

FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\requests\adapters.py", line 370, in send
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 544, in urlopen
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 341, in _make_request
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 762, in _validate_conn
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connection.py", line 238, in connect
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\util\ssl_.py", line 255, in ssl_wrap_socket
requests.packages.urllib3.exceptions.SSLError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python\32-bit\3.4\lib\threading.py", line 921, in _bootstrap_inner
  File "c:\python\32-bit\3.4\lib\threading.py", line 869, in run
  File "downloader.py", line 65, in goDownloadBackground
  File "downloader.py", line 106, in doDownload
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 476, in get
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 464, in request
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 602, in send
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 602, in <listcomp>
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 195, in resolve_redirects
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 576, in send
  File "c:\Python34\lib\site-packages\requests\adapters.py", line 431, in send
requests.exceptions.SSLError: [Errno 2] No such file or directory
```

I think it's saying that I do not have Minecraft since I'm using a cracked version from TeamExteme to do this. If that's not the case, then allow me to state some things that I did before executing this.

1) I downloaded Minecraft Agrarian Skies 2 in the following link: mods.curse.com/modpacks/minecraft/225550-agrarian-skies-2

2) I also downloaded forge, it's version is 10.13.3.1387 - this version is for Minecraft 1.7.10 as follows:
files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.7.10.html

3) I tried copying the file directly into Minecraft as the picture shows:
![install](https://cloud.githubusercontent.com/assets/26916297/24689600/d3548e00-19f1-11e7-9aeb-061f7736d39d.PNG)
The left tab contains the modpack that inside the "override" folder (as path is shown). Whilst the right side is the Minecraft Forge Profile that has been set up and pre-runned. I copied everything from the left and dragged it to the right, replacing 2 files. After running it gave me this error:
![error](https://cloud.githubusercontent.com/assets/26916297/24689637/0b24822c-19f2-11e7-9c83-a65fc34d67bd.PNG)

I can't locate the log folder either

**Comment by insuusvenerati** [comment]
I think this tool is designed for Linux and MacOS

**Comment by TOLoneWolf** [comment]
the compiled exe is old and broken since some things where changed on curse. Source .py files work and other forks of this work on windows as well.
