### ISSUE TITLE
File Not Found Error

### ISSUE THREAD

**Issue by LycanBlackpaw** [portablejim/curseDownloader#46]
So, first off, this REALLY needs more documentation. It says that it's just 'download and run', but clearly that's not the case.

I'm getting a File Not Found error, repeatedly. I've downloaded Python, set it running, and done everything I can think of to figure this out-I wish I knew more about Python.

Here's the error:
`106 files to download
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\util\ssl_.py", l
ine 253, in ssl_wrap_socket
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\requests\adapters.py", line 370, in send
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.p
y", line 544, in urlopen
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.p
y", line 341, in _make_request
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.p
y", line 762, in _validate_conn
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connection.py",
line 238, in connect
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\util\ssl_.py", l
ine 255, in ssl_wrap_socket
requests.packages.urllib3.exceptions.SSLError: [Errno 2] No such file or directo
ry

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python\32-bit\3.4\lib\threading.py", line 921, in _bootstrap_inner
  File "c:\python\32-bit\3.4\lib\threading.py", line 869, in run
  File "downloader.py", line 65, in goDownloadBackground
  File "downloader.py", line 134, in doDownload
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 476, in get
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 464, in reques
t
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 602, in send
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 602, in <listc
omp>
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 195, in resolv
e_redirects
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 576, in send
  File "c:\Python34\lib\site-packages\requests\adapters.py", line 431, in send
requests.exceptions.SSLError: [Errno 2] No such file or directory

`

**Comment by TOLoneWolf** [comment]
the compiled exe for this is old and broken. He has only updated the source python files. If you have installed python and all the other dependencies then you can run the downloader.py by downloading the source. Or try one of the other forks.
