### ISSUE TITLE
Exceeded 30 redirects.

### ISSUE THREAD

**Issue by iaidan** [portablejim/curseDownloader#47]
Not sure how to fix this.

Modpack:  Space Astronomy 2 v1.1.5.zip

 python3.4 downloader.py --manifest manifest.json --nogui

Cache path : /root/.cache/cursePackDownloader/curseCache
159 files to download
Traceback (most recent call last):
  File "/home/minecraft/multicraft/scripts/curse/downloader.py", line 234, in <module>
    doDownload(args.manifest)
  File "/home/minecraft/multicraft/scripts/curse/downloader.py", line 165, in doDownload
    for redirect in sess.resolve_redirects(projectResponse, projectResponse.request):
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 111, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

**Comment by solarus** [comment]
Also had this issue. For me it failed to download modtweaker. The problem seems to be on the curse homepage though, i.e. I also got the same issue in a browser while accessing the project via the project id (220954) or the name directly, i.e.:

https://minecraft.curseforge.com/projects/220954
or
https://minecraft.curseforge.com/projects/modtweaker

Worked around by downloading manually via https://minecraft.curseforge.com/projects/modtweaker/files/FILE_ID_HERE/download` and placing the file in the download cache.

**Comment by fedeb95** [comment]
I'm facing the same issue. Where can I found the download cache?

**Comment by fedeb95** [comment]
Ok, found soon after. If someone needs it, run a find for the directory curseCache, there create a directory with the project id form the manifets: inside create a directory with the file id form the manifest, then place the manually downloaded jar as suggested above inside this directory
