### ISSUE TITLE
AttributeError: 'Response' object has no attribute 'is_redirect'

### ISSUE THREAD

**Issue by megalous** [portablejim/curseDownloader#5]
Hello I got an AttributeError: 'Response' object has no attribute 'is_redirect' while trying to download the Horizon: Daybreaker Modpack 1.0.3 with you downloading script.

The console output with and without gui portable option:

user@user-pc ~ $ python3.4 /home/user/Downloads/curseupdater/downloader.py 
96 files to download
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/Downloads/curseupdater/downloader.py", line 67, in goDownloadBackground
    doDownload(self.manifestPath.get())
  File "/home/user/Downloads/curseupdater/downloader.py", line 146, in doDownload
    while fileResponse.is_redirect:
AttributeError: 'Response' object has no attribute 'is_redirect'

user@user-pc ~ $ python3.4 /home/user/Downloads/curseupdater/downloader.py --nogui --portable --manifest /home/user/Downloads/HDB/manifest.json 
96 files to download
Traceback (most recent call last):
  File "/home/user/Downloads/curseupdater/downloader.py", line 206, in <module>
    doDownload(args.manifest)
  File "/home/user/Downloads/curseupdater/downloader.py", line 146, in doDownload
    while fileResponse.is_redirect:
AttributeError: 'Response' object has no attribute 'is_redirect'

user@user-pc ~ $ python3.4 /home/user/Downloads/curseupdater/downloader.py --nogui --manifest /home/user/Downloads/HDB/manifest.json 96 files to download
Traceback (most recent call last):
  File "/home/user/Downloads/curseupdater/downloader.py", line 206, in <module>
    doDownload(args.manifest)
  File "/home/user/Downloads/curseupdater/downloader.py", line 146, in doDownload
    while fileResponse.is_redirect:
AttributeError: 'Response' object has no attribute 'is_redirect'

**Comment by gazpachoking** [comment]
This will be because you have an older requests version (`is_redirect` was added in 2.3.) That being said, a requests session handles those redirects already, so #6 will allow older requests versions to work as this code isn't needed.

**Comment by megalous** [comment]
Thank you very much for pointing to the cause of the error. I had to install python3-requests 2.3.0-1 from https://launchpad.net/ubuntu/utopic/amd64/python3-requests/2.3.0-1, because the repositories for Ubuntu 14.04/Linux Mint 17.2 supply only version 2.2.1.
