### ISSUE TITLE
Arch Linux `Exception in thread Thread-1:`

### ISSUE THREAD

**Issue by Physicist1616** [portablejim/curseDownloader#51]
Maybe two issues, but maybe just one issue like "arch support please"; your project, your call, my thanks if you can accomodate, and my thanks anyway for in-general support for non-proprietary game clients.

Arch Linux (if it matters, default python is python3, but I have both installed) crash.
I can't correctly `browse` to anything (KDE Plasma) because the folders don't have names next to them.  

This is what happens when I type the path of a manifest.json file, note that ctrl-c did nothing, I had to ctrl-z and kill it:

[tim@arch temp]$ ./cursePackDownloader-0.3-linux64 
Cache path : /home/tim/.cache/cursePackDownloader/curseCache
111 files to download
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "threading.py", line 862, in run
  File "downloader.py", line 72, in goDownloadBackground
  File "downloader.py", line 132, in doDownload
AttributeError: 'NoneType' object has no attribute 'setOutput'

^C

^Z
[2]+  Stopped                 ./cursePackDownloader-0.3-linux64
[tim@arch temp]$ kill %2

**Comment by Physicist1616** [comment]
Additional info about python versioning in Arch, `python` is symlinked to `python3`, and the executable for 2 is predictably `python2`.
`[tim@arch ~]$ ls -lah /bin/python*`
`lrwxrwxrwx 1 root root    7 Jul 19 09:53 /bin/python -> python3`
`lrwxrwxrwx 1 root root    9 Sep 19 07:26 /bin/python2 -> python2.7`
`-rwxr-xr-x 1 root root 5.8K Sep 19 07:26 /bin/python2.7`
`-rwxr-xr-x 1 root root 1.7K Sep 19 07:26 /bin/python2.7-config`
`lrwxrwxrwx 1 root root   16 Sep 19 07:26 /bin/python2-config -> python2.7-config`
`lrwxrwxrwx 1 root root    9 Jul 19 09:53 /bin/python3 -> python3.6`
`-rwxr-xr-x 2 root root  11K Jul 19 09:54 /bin/python3.6`
`lrwxrwxrwx 1 root root   17 Jul 19 09:53 /bin/python3.6-config -> python3.6m-config`
`-rwxr-xr-x 2 root root  11K Jul 19 09:54 /bin/python3.6m`
`-rwxr-xr-x 1 root root 3.1K Jul 19 09:53 /bin/python3.6m-config`
`lrwxrwxrwx 1 root root   16 Jul 19 09:53 /bin/python3-config -> python3.6-config`
`lrwxrwxrwx 1 root root   14 Jul 19 09:53 /bin/python-config -> python3-config`
`[tim@arch ~]$ `

**Comment by UtechtDustin** [comment]
same issue here, workaround ?

**Comment by Dijkstra1-zz** [comment]
Downloading the source and running that seems to work
